version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  nimbus:
    image: mtunique/jstorm
    # build: ./jstorm
    container_name: nimbus
    command: jstorm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  supervisor:
    image: mtunique/jstorm
    # build: ./jstorm
    container_name: supervisor
    command: jstorm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

  ui:
    image: cranelana/jstorm-ui-2.2.1
    # build: ./ui
    container_name: ui
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    ports:
      - 8090:8080
